[Console-UI]  Make UI changes for DL and expiry queue
EnMasseProject/enmasse pull request #5143
Opened 2020-08-17 18:30 UTC by drcoolsanjeev

### Type of change

- Enhancement / new feature

### Description

 Make UI changes to enable configuration for DeadLetter and expiry address in create/edit address of type queue and subscription 
Add a label for DeadLetter type in address list page
 Show DeadLetter and expiry queue in address detail header 

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

2020-08-18 14:22 UTC, anukritijha commented on console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx
> +                <Deadletter
The component names are inconsistent. Either should have Queue as the suffix or both should exclude it.

2020-08-18 14:23 UTC, anukritijha commented on console/console-init/ui/src/modules/address/components/ExpiryQueue/ExpiryQueue.tsx
> +      label="Expiry Queue"
The label should be changed to Expiry Address everywhere.

2020-08-19 09:25 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx
> +  onExpiryAddressSelect?: (value: string) => void;
Use event name with standard.
onExpiryAddressSelect==>onSelectExpiryAddress

2020-08-19 09:25 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx
> +  onExpiryAddressSelect,
Use event name with standard.
onExpiryAddressSelect==>onSelectExpiryAddress

2020-08-19 09:25 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx
> +                  onExpiryAddressSelect={onExpiryAddressSelect}
Use event name with standard.
onExpiryAddressSelect==>onSelectExpiryAddress

2020-08-19 09:26 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/components/ExpiryQueue/ExpiryQueue.tsx
> +  onExpiryAddressSelect,
Use event name with standard.
onExpiryAddressSelect==>onSelectExpiryAddress

2020-08-19 09:26 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx
> +  const onExpiryAddressSelect = (value: string) => {
Use event name with standard.
onExpiryAddressSelect==>onSelectExpiryAddress

2020-08-19 09:27 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx
> +      onExpiryAddressSelect={onExpiryAddressSelect}
Use event name with standard.
onExpiryAddressSelect==>onSelectExpiryAddress

2020-08-19 09:29 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/components/ExpiryQueue/ExpiryQueue.tsx
> +export const ExpiryAddress: React.FunctionComponent<IExpiryAddressProps> = ({
Change folder and file name with postfix Address
`ExpiryAddress/ExpiryAddress.tsx`

2020-08-19 09:31 UTC, ajaypratap003 requested changes
Added few suggestions.

2020-08-19 10:54 UTC, rkpattnaik780 commented on console/console-init/ui/src/modules/address/components/DeadLetterAddress/index.ts
> +export * from "./DeadLetterAddress";
LICENSE is missing.

2020-08-19 11:11 UTC, rkpattnaik780 requested changes
I am observing this phenomenon. Empty deadletter address and expiry address are getting added.

![deadletter](https://user-images.githubusercontent.com/23582438/90627914-4dd4e580-e23a-11ea-8c83-5aebddc5ba3b.gif)

2020-08-20 06:20 UTC, suyash-naithani approved these changes

2020-08-20 06:56 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/address/dialogs/EditAddress/EditAddress.tsx
> +    if (!value || value.trim() === "" || value.trim() === "null") {
I think null check is wrong. It shoud be null `value.trim() ===null` rather than string

2020-08-20 11:12 UTC, anukritijha requested changes

2020-08-20 11:12 UTC, anukritijha commented on console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx
> +        const deadletter_addresses = await client.query<IAddressResponse>({
Please use camel case.

2020-08-20 11:12 UTC, anukritijha commented on console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx
> +          if (deadletter && deadletter.trim() !== "") {
Please rename this to deadletterAddress.

2020-08-20 11:12 UTC, anukritijha commented on console/console-init/ui/src/modules/address/dialogs/EditAddress/EditAddress.tsx
> +  const dlq_addresses = useQuery<IAddressResponse>(
Please use camel case in variable names.

2020-08-20 11:12 UTC, anukritijha commented on console/console-init/ui/src/modules/address/dialogs/EditAddress/EditAddress.tsx
> +  let deadLetters: IDropdownOption[] = [{ key: " ", value: " ", label: " " }];
As stated above, please rename.

2020-08-24 17:21 UTC, k-wall commented
@suyash-naithani @drcoolsanjeev I took the liberty of the rebasing the patch and I needed to make a change to fix the field names.   We'd renamed `deadLetterAddress` => `deadletter` and `expiryAddress` => `expiry`.  The reason for this is to following the established naming convention already established by the topic `field`.

2020-08-24 18:11 UTC, k-wall commented
There's still a defect which showed against the real backend.  It appears when removing a deadletter or expiry assignment from a queue.  In this case the server requires that a JSON patch [remove](https://tools.ietf.org/html/rfc6902#page-6) is used to remove the element.   However it is only valid to send a JSON patch with a remove instruction when the document actually contains the element to be removed.  

rfc6902 remove says "The target location MUST exist for the operation to be successful."

I've changed the mock to give equivalent behaviour.   You'll need to add some logic to `getJsonPatchObject` to use:
* an `add` operation when adding a deadletter/expiry when setting one,
* an `remove` operation when removing a deadletter/expiry when removing one
* an `replace` operation when changing one.

(My original intent was that the UI would use a library (like https://www.npmjs.com/package/fast-json-patch) to produce the JSON patch by comparing the old object with the new one.  That would save you hand crafting the document).

2020-08-25 13:26 UTC, k-wall approved these changes
Looks reasonable to me.

2020-08-25 13:40 UTC, anukritijha approved these changes

2020-08-25 13:42 UTC, rkpattnaik780 approved these changes

2020-08-25 14:07 UTC, suyash-naithani approved these changes

2020-08-25 14:37 UTC, merged