Review device
EnMasseProject/enmasse pull request #5153
Opened 2020-08-21 08:36 UTC by drcoolsanjeev

### Type of change

- Enhancement

### Description

Add Review component for metadata
![image](https://user-images.githubusercontent.com/29524461/90870619-78987880-e3b7-11ea-9e70-2097948fd7c3.png)

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

2020-08-24 09:37 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/iot-device/utils/utils.ts
>            deviceDetail.registration.defaults = JSON.stringify(
use convertJsonToStringAndValidate for stringfy and error handling.

2020-08-24 09:37 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/iot-device/utils/utils.ts
>            deviceDetail.registration.ext = JSON.stringify(registration.ext);
use convertJsonToStringAndValidate for stringfy and error handling.

2020-08-24 09:40 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/iot-device/components/ReviewDevice/MetaDataReviewRows.tsx
> +const MetaDataReviewRows: React.FC<IMetaDataReviewRowProps> = ({
This component is generic and will use in other pages as well. I would suggest generic name MetadataView.

2020-08-24 09:43 UTC, ajaypratap003 commented on console/console-init/ui/src/modules/iot-device/components/ReviewDevice/MetaDataReviewRow.tsx
> +const styles = StyleSheet.create({
Can you please try to use `rem` for css. It will help later when we will remove aphrodite lib.

2020-08-24 09:44 UTC, ajaypratap003 requested changes
Added some review comments

2020-08-24 13:40 UTC, ajaypratap003 approved these changes

2020-08-25 06:28 UTC, anukritijha approved these changes

2020-08-25 06:46 UTC, rkpattnaik780 approved these changes

2020-08-25 07:13 UTC, merged