[Console IoT]- Fix app crashing on uploading a .pem file for a TLS certificate
EnMasseProject/enmasse pull request #5187
Opened 2020-09-04 07:43 UTC by suyash-naithani

### Type of change

- Bugfix

### Description

 Fix app crashing on uploading a .pem file for a TLS certificate

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

2020-09-04 11:04 UTC, anukritijha requested changes

2020-09-04 11:04 UTC, anukritijha commented on console/console-init/ui/src/modules/project/utils/utils.ts
> +        protocols.map((protocol: string) => {
map should be used only when you want to return an array. For cases when you're not returning anything, use forEach.

2020-09-07 04:44 UTC, drcoolsanjeev approved these changes

2020-09-09 09:18 UTC, anukritijha approved these changes

2020-09-09 17:29 UTC, merged