Issue 5272
EnMasseProject/enmasse pull request #5273
Opened 2021-03-08 16:22 UTC by k-wall

### Type of change

- Enhancement / new feature

### Description

Support router policy maxMessageSize

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

2021-03-08 16:30 UTC, rgodfrey submitted a review, later dismissed
LGTM

2021-03-08 16:33 UTC, hmaclean73 requested changes
One minor change.

2021-03-08 16:33 UTC, hmaclean73 commented on documentation/modules/ref-standard-infra-config-fields.adoc
> +|`router.policy.maxMessageSize` |The maximum size in bytes of AMQP message transfers allowed for this router. This limit is applied to transfers to/from client connections. A value of zero disables t
```suggestion
|`router.policy.maxMessageSize` |Specifies the maximum size in bytes of AMQP message transfers allowed for this router. This limit is applied to transfers to/from client connections. A value of zero disables this limit.
```

2021-03-09 13:16 UTC, hmaclean73 approved these changes
LGTM

2021-03-09 19:48 UTC, k-wall commented
@enmasse-ci run tests profile=acceptance ocp4

2021-03-10 09:34 UTC, merged