Alternative bundle for OCP 3.11
EnMasseProject/enmasse pull request #5287
Opened 2021-03-15 20:15 UTC by k-wall

### Type of change

- Documentation

### Description

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

2021-03-15 20:19 UTC, k-wall commented on documentation/common/proc-download-procedure.adoc
> +* Download and extract the `{ZipInstallFile}` file from the {ZipDownload}.
So for this release there will be two bundles, one suitable for < Kube 1.16 (and OpenShift 3.11) and another suitable for newer Kubernetes and all OpenShift 4 versions.  How best shall this be presented?   Feel free to commit to this PR or I'll make a suggestion tomorrow.  @hmaclean73

2021-03-16 12:37 UTC, hmaclean73 requested changes
Just a few changes

2021-03-16 12:37 UTC, hmaclean73 commented on documentation/common/proc-download-procedure.adoc
> +* Download one of the releases from the link:https://github.com/EnMasseProject/enmasse/releases[GitHub repository]. There are two versions bundles of the bundle provided: `enmasse-<version>.tgz` and
```suggestion
* Download one of the releases from the link:https://github.com/EnMasseProject/enmasse/releases[GitHub repository]. There are two versions of the bundle provided: `enmasse-<version>.tgz` and `enmasse-prekube1_16-<version>.tgz`.
```

2021-03-16 12:37 UTC, hmaclean73 commented on documentation/common/proc-download-procedure.adoc
> +On {KubePlatform} 3.11 and before choose `enmasse-prekube1_16-<version>.tgz`
```suggestion
On {KubePlatform} 3.11 and before, choose `enmasse-prekube1_16-<version>.tgz`.
```

2021-03-16 12:37 UTC, hmaclean73 commented on documentation/common/proc-download-procedure.adoc
> +On {KubePlatform} 1.15 and below choose `enmasse-prekube1_16-<version>.tgz`
```suggestion
On {KubePlatform} 1.15 and below, choose `enmasse-prekube1_16-<version>.tgz`.
```

2021-03-16 12:37 UTC, hmaclean73 commented on documentation/common/proc-download-procedure.adoc
> +otherwise take `enmasse-<version>.tgz`.
```suggestion
Otherwise, choose `enmasse-<version>.tgz`.
```

2021-03-16 13:50 UTC, hmaclean73 approved these changes
LGTM

2021-03-16 14:08 UTC, merged